var logo_linux_default = "https://img.icons8.com/color/48/000000/linux--v1.png"

let oslist = [
  {
    logo: "https://img.icons8.com/fluency/48/000000/windows-11.png",
    name: "Windows 11 Insider Preview (Dev)",
    type: "Insider Preview",
    build: "22557.1",
    codename: "N/A",
    rel: "N/A",
    eol: "N/A",
    platform: "x64, ARM",
  },
  {
    logo: "https://img.icons8.com/fluency/48/000000/windows-11.png",
    name: "Windows 11",
    type: "Stable",
    build: "21H2",
    codename: "Sun Valley",
    rel: "2021",
    eol: "N/A",
    platform: "x64, ARM",
  },
  {
    logo: "https://img.icons8.com/color/48/000000/windows-10.png",
    name: "Windows 10 (21H2)",
    type: "Stable",
    build: "21H2",
    codename: "N/A",
    rel: "2021",
    eol: "2025",
    platform: "x64, x32, ARM",
  },
  {
    logo: "https://img.icons8.com/color/48/000000/windows-10.png",
    name: "Windows 10",
    type: "Stable",
    build: "21H1",
    codename: "Redstone",
    rel: "2015",
    eol: "2025",
    platform: "x64, x32, ARM",
  },
  {
    logo: "https://img.icons8.com/color/48/000000/windows8.png",
    name: "Windows RT",
    type: "N/A",
    build: "6.3.9600",
    codename: "RT",
    rel: "October 26th, 2012",
    eol: "January 10th, 2023",
    platform: "ARM",
  },
  {
    logo: "https://img.icons8.com/color/48/000000/windows8.png",
    name: "Windows 8/8.1",
    type: "Stable",
    build: "NT 6.2",
    codename: "Blue",
    rel: "2013",
    eol: "2023",
    platform: "x64, x32 ARM",
  },
  {
    logo: "https://www.logo.wine/a/logo/Windows_7/Windows_7-Logo.wine.svg",
    name: "Windows 7",
    type: "Stable",
    build: "NT 6.1",
    codename: "Blackcomb",
    rel: "2009",
    eol: "2020",
    platform: "x64, x32",
  },
  {
    name: "Windows XP",
    type: "Stable",
    build: "NT 5.1",
    codename: "Whistler",
    rel: "2001",
    eol: "2014",
    platform: "x64, x32",
  },
  {
    logo: <img src=logo_linux_default/>,
    name: "Ubuntu 20.04",
    type: "LTS",
    build: "N/A",
    codename: "Focal Fossa",
    rel: "April 2020",
    eol: "Contribute",
    platform: "x64, x32, arm64, pi",
  },
];
export default oslist;
